// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createJob = `-- name: CreateJob :one
INSERT INTO ocr_jobs (
  document_version_id,
  job_type,
  task_id,
  status,
  payload_json
) VALUES ($1, $2, $3, $4, $5)
RETURNING id, document_version_id, job_type, task_id, status, payload_json, attempt_count, error_message, created_at, updated_at, finished_at
`

type CreateJobParams struct {
	DocumentVersionID pgtype.UUID `json:"document_version_id"`
	JobType           string      `json:"job_type"`
	TaskID            string      `json:"task_id"`
	Status            string      `json:"status"`
	PayloadJson       []byte      `json:"payload_json"`
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (OcrJob, error) {
	row := q.db.QueryRow(ctx, createJob,
		arg.DocumentVersionID,
		arg.JobType,
		arg.TaskID,
		arg.Status,
		arg.PayloadJson,
	)
	var i OcrJob
	err := row.Scan(
		&i.ID,
		&i.DocumentVersionID,
		&i.JobType,
		&i.TaskID,
		&i.Status,
		&i.PayloadJson,
		&i.AttemptCount,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getJobByID = `-- name: GetJobByID :one
SELECT id, document_version_id, job_type, task_id, status, payload_json, attempt_count, error_message, created_at, updated_at, finished_at FROM ocr_jobs
WHERE id = $1
`

func (q *Queries) GetJobByID(ctx context.Context, id pgtype.UUID) (OcrJob, error) {
	row := q.db.QueryRow(ctx, getJobByID, id)
	var i OcrJob
	err := row.Scan(
		&i.ID,
		&i.DocumentVersionID,
		&i.JobType,
		&i.TaskID,
		&i.Status,
		&i.PayloadJson,
		&i.AttemptCount,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getUsageSummary = `-- name: GetUsageSummary :one
SELECT
  COUNT(DISTINCT d.id)::bigint AS document_count,
  COALESCE(SUM(d.size_bytes), 0)::bigint AS storage_bytes,
  COUNT(DISTINCT u.id)::bigint AS user_count
FROM users u
LEFT JOIN documents d ON d.org_id = u.org_id AND d.deleted_at IS NULL
WHERE u.org_id = $1
`

type GetUsageSummaryRow struct {
	DocumentCount int64 `json:"document_count"`
	StorageBytes  int64 `json:"storage_bytes"`
	UserCount     int64 `json:"user_count"`
}

func (q *Queries) GetUsageSummary(ctx context.Context, orgID pgtype.UUID) (GetUsageSummaryRow, error) {
	row := q.db.QueryRow(ctx, getUsageSummary, orgID)
	var i GetUsageSummaryRow
	err := row.Scan(&i.DocumentCount, &i.StorageBytes, &i.UserCount)
	return i, err
}

const listJobs = `-- name: ListJobs :many
SELECT id, document_version_id, job_type, task_id, status, payload_json, attempt_count, error_message, created_at, updated_at, finished_at FROM ocr_jobs
ORDER BY created_at DESC
LIMIT $1
`

func (q *Queries) ListJobs(ctx context.Context, limit int32) ([]OcrJob, error) {
	rows, err := q.db.Query(ctx, listJobs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OcrJob
	for rows.Next() {
		var i OcrJob
		if err := rows.Scan(
			&i.ID,
			&i.DocumentVersionID,
			&i.JobType,
			&i.TaskID,
			&i.Status,
			&i.PayloadJson,
			&i.AttemptCount,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrganizations = `-- name: ListOrganizations :many
SELECT id, name, slug, created_at FROM organizations
ORDER BY name
`

func (q *Queries) ListOrganizations(ctx context.Context) ([]Organization, error) {
	rows, err := q.db.Query(ctx, listOrganizations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Organization
	for rows.Next() {
		var i Organization
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuotas = `-- name: ListQuotas :many
SELECT id, org_id, target_type, target_id, max_storage_bytes, max_document_count, created_at, updated_at FROM quotas
WHERE org_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListQuotas(ctx context.Context, orgID pgtype.UUID) ([]Quota, error) {
	rows, err := q.db.Query(ctx, listQuotas, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Quota
	for rows.Next() {
		var i Quota
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.TargetType,
			&i.TargetID,
			&i.MaxStorageBytes,
			&i.MaxDocumentCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRetentionPolicies = `-- name: ListRetentionPolicies :many
SELECT id, org_id, name, applies_to_collection_id, retention_days, archive_after_days, delete_after_days, enabled, created_at, updated_at FROM retention_policies
WHERE org_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListRetentionPolicies(ctx context.Context, orgID pgtype.UUID) ([]RetentionPolicy, error) {
	rows, err := q.db.Query(ctx, listRetentionPolicies, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RetentionPolicy
	for rows.Next() {
		var i RetentionPolicy
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.AppliesToCollectionID,
			&i.RetentionDays,
			&i.ArchiveAfterDays,
			&i.DeleteAfterDays,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSystemSettings = `-- name: ListSystemSettings :many
SELECT id, org_id, setting_key, setting_value, updated_at FROM system_settings
WHERE org_id = $1
ORDER BY setting_key
`

func (q *Queries) ListSystemSettings(ctx context.Context, orgID pgtype.UUID) ([]SystemSetting, error) {
	rows, err := q.db.Query(ctx, listSystemSettings, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SystemSetting
	for rows.Next() {
		var i SystemSetting
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.SettingKey,
			&i.SettingValue,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJobStatus = `-- name: UpdateJobStatus :exec
UPDATE ocr_jobs
SET status = $2,
    attempt_count = $3,
    error_message = $4,
    updated_at = now(),
    finished_at = CASE WHEN $2 IN ('completed', 'failed') THEN now() ELSE finished_at END
WHERE task_id = $1
`

type UpdateJobStatusParams struct {
	TaskID       string      `json:"task_id"`
	Status       string      `json:"status"`
	AttemptCount int32       `json:"attempt_count"`
	ErrorMessage pgtype.Text `json:"error_message"`
}

func (q *Queries) UpdateJobStatus(ctx context.Context, arg UpdateJobStatusParams) error {
	_, err := q.db.Exec(ctx, updateJobStatus,
		arg.TaskID,
		arg.Status,
		arg.AttemptCount,
		arg.ErrorMessage,
	)
	return err
}

const upsertQuota = `-- name: UpsertQuota :one
INSERT INTO quotas (
  org_id,
  target_type,
  target_id,
  max_storage_bytes,
  max_document_count
) VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (org_id, target_type, target_id)
DO UPDATE SET
  max_storage_bytes = EXCLUDED.max_storage_bytes,
  max_document_count = EXCLUDED.max_document_count,
  updated_at = now()
RETURNING id, org_id, target_type, target_id, max_storage_bytes, max_document_count, created_at, updated_at
`

type UpsertQuotaParams struct {
	OrgID            pgtype.UUID `json:"org_id"`
	TargetType       string      `json:"target_type"`
	TargetID         pgtype.UUID `json:"target_id"`
	MaxStorageBytes  int64       `json:"max_storage_bytes"`
	MaxDocumentCount int32       `json:"max_document_count"`
}

func (q *Queries) UpsertQuota(ctx context.Context, arg UpsertQuotaParams) (Quota, error) {
	row := q.db.QueryRow(ctx, upsertQuota,
		arg.OrgID,
		arg.TargetType,
		arg.TargetID,
		arg.MaxStorageBytes,
		arg.MaxDocumentCount,
	)
	var i Quota
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.TargetType,
		&i.TargetID,
		&i.MaxStorageBytes,
		&i.MaxDocumentCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertRetentionPolicy = `-- name: UpsertRetentionPolicy :one
INSERT INTO retention_policies (
  id,
  org_id,
  name,
  applies_to_collection_id,
  retention_days,
  archive_after_days,
  delete_after_days,
  enabled
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (id)
DO UPDATE SET
  name = EXCLUDED.name,
  applies_to_collection_id = EXCLUDED.applies_to_collection_id,
  retention_days = EXCLUDED.retention_days,
  archive_after_days = EXCLUDED.archive_after_days,
  delete_after_days = EXCLUDED.delete_after_days,
  enabled = EXCLUDED.enabled,
  updated_at = now()
RETURNING id, org_id, name, applies_to_collection_id, retention_days, archive_after_days, delete_after_days, enabled, created_at, updated_at
`

type UpsertRetentionPolicyParams struct {
	ID                    pgtype.UUID `json:"id"`
	OrgID                 pgtype.UUID `json:"org_id"`
	Name                  string      `json:"name"`
	AppliesToCollectionID pgtype.UUID `json:"applies_to_collection_id"`
	RetentionDays         int32       `json:"retention_days"`
	ArchiveAfterDays      pgtype.Int4 `json:"archive_after_days"`
	DeleteAfterDays       pgtype.Int4 `json:"delete_after_days"`
	Enabled               bool        `json:"enabled"`
}

func (q *Queries) UpsertRetentionPolicy(ctx context.Context, arg UpsertRetentionPolicyParams) (RetentionPolicy, error) {
	row := q.db.QueryRow(ctx, upsertRetentionPolicy,
		arg.ID,
		arg.OrgID,
		arg.Name,
		arg.AppliesToCollectionID,
		arg.RetentionDays,
		arg.ArchiveAfterDays,
		arg.DeleteAfterDays,
		arg.Enabled,
	)
	var i RetentionPolicy
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.AppliesToCollectionID,
		&i.RetentionDays,
		&i.ArchiveAfterDays,
		&i.DeleteAfterDays,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSystemSetting = `-- name: UpsertSystemSetting :one
INSERT INTO system_settings (
  org_id,
  setting_key,
  setting_value
) VALUES ($1, $2, $3)
ON CONFLICT (org_id, setting_key)
DO UPDATE SET
  setting_value = EXCLUDED.setting_value,
  updated_at = now()
RETURNING id, org_id, setting_key, setting_value, updated_at
`

type UpsertSystemSettingParams struct {
	OrgID        pgtype.UUID `json:"org_id"`
	SettingKey   string      `json:"setting_key"`
	SettingValue []byte      `json:"setting_value"`
}

func (q *Queries) UpsertSystemSetting(ctx context.Context, arg UpsertSystemSettingParams) (SystemSetting, error) {
	row := q.db.QueryRow(ctx, upsertSystemSetting, arg.OrgID, arg.SettingKey, arg.SettingValue)
	var i SystemSetting
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.SettingKey,
		&i.SettingValue,
		&i.UpdatedAt,
	)
	return i, err
}
