// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit.sql

package dbgen

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertAuditEvent = `-- name: InsertAuditEvent :one
INSERT INTO audit_events (
  org_id,
  actor_user_id,
  actor_role,
  action,
  resource_type,
  resource_id,
  ip_address,
  user_agent,
  request_id,
  payload_json
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING id, org_id, actor_user_id, actor_role, action, resource_type, resource_id, ip_address, user_agent, request_id, payload_json, created_at
`

type InsertAuditEventParams struct {
	OrgID        pgtype.UUID `json:"org_id"`
	ActorUserID  pgtype.UUID `json:"actor_user_id"`
	ActorRole    string      `json:"actor_role"`
	Action       string      `json:"action"`
	ResourceType string      `json:"resource_type"`
	ResourceID   pgtype.UUID `json:"resource_id"`
	IpAddress    *netip.Addr `json:"ip_address"`
	UserAgent    string      `json:"user_agent"`
	RequestID    string      `json:"request_id"`
	PayloadJson  []byte      `json:"payload_json"`
}

func (q *Queries) InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) (AuditEvent, error) {
	row := q.db.QueryRow(ctx, insertAuditEvent,
		arg.OrgID,
		arg.ActorUserID,
		arg.ActorRole,
		arg.Action,
		arg.ResourceType,
		arg.ResourceID,
		arg.IpAddress,
		arg.UserAgent,
		arg.RequestID,
		arg.PayloadJson,
	)
	var i AuditEvent
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ActorUserID,
		&i.ActorRole,
		&i.Action,
		&i.ResourceType,
		&i.ResourceID,
		&i.IpAddress,
		&i.UserAgent,
		&i.RequestID,
		&i.PayloadJson,
		&i.CreatedAt,
	)
	return i, err
}

const listAuditEvents = `-- name: ListAuditEvents :many
SELECT id, org_id, actor_user_id, actor_role, action, resource_type, resource_id, ip_address, user_agent, request_id, payload_json, created_at FROM audit_events
WHERE org_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListAuditEventsParams struct {
	OrgID  pgtype.UUID `json:"org_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) ListAuditEvents(ctx context.Context, arg ListAuditEventsParams) ([]AuditEvent, error) {
	rows, err := q.db.Query(ctx, listAuditEvents, arg.OrgID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditEvent
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ActorUserID,
			&i.ActorRole,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.IpAddress,
			&i.UserAgent,
			&i.RequestID,
			&i.PayloadJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditEventsFiltered = `-- name: ListAuditEventsFiltered :many
SELECT id, org_id, actor_user_id, actor_role, action, resource_type, resource_id, ip_address, user_agent, request_id, payload_json, created_at FROM audit_events
WHERE org_id = $1
  AND ($4::text = '' OR action = $4)
  AND ($5::timestamptz IS NULL OR created_at >= $5)
  AND ($6::timestamptz IS NULL OR created_at <= $6)
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListAuditEventsFilteredParams struct {
	OrgID   pgtype.UUID        `json:"org_id"`
	Limit   int32              `json:"limit"`
	Offset  int32              `json:"offset"`
	Column4 string             `json:"column_4"`
	Column5 pgtype.Timestamptz `json:"column_5"`
	Column6 pgtype.Timestamptz `json:"column_6"`
}

func (q *Queries) ListAuditEventsFiltered(ctx context.Context, arg ListAuditEventsFilteredParams) ([]AuditEvent, error) {
	rows, err := q.db.Query(ctx, listAuditEventsFiltered,
		arg.OrgID,
		arg.Limit,
		arg.Offset,
		arg.Column4,
		arg.Column5,
		arg.Column6,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditEvent
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ActorUserID,
			&i.ActorRole,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.IpAddress,
			&i.UserAgent,
			&i.RequestID,
			&i.PayloadJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
