// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: comments.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createComment = `-- name: CreateComment :one
INSERT INTO comments (
  document_id,
  author_user_id,
  body
) VALUES ($1, $2, $3)
RETURNING id, document_id, author_user_id, body, created_at
`

type CreateCommentParams struct {
	DocumentID   pgtype.UUID `json:"document_id"`
	AuthorUserID pgtype.UUID `json:"author_user_id"`
	Body         string      `json:"body"`
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, createComment, arg.DocumentID, arg.AuthorUserID, arg.Body)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.AuthorUserID,
		&i.Body,
		&i.CreatedAt,
	)
	return i, err
}

const listCommentsByDocumentID = `-- name: ListCommentsByDocumentID :many
SELECT
  c.id, c.document_id, c.author_user_id, c.body, c.created_at,
  u.full_name AS author_name
FROM comments c
JOIN users u ON u.id = c.author_user_id
WHERE c.document_id = $1
ORDER BY c.created_at DESC
`

type ListCommentsByDocumentIDRow struct {
	ID           pgtype.UUID        `json:"id"`
	DocumentID   pgtype.UUID        `json:"document_id"`
	AuthorUserID pgtype.UUID        `json:"author_user_id"`
	Body         string             `json:"body"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	AuthorName   string             `json:"author_name"`
}

func (q *Queries) ListCommentsByDocumentID(ctx context.Context, documentID pgtype.UUID) ([]ListCommentsByDocumentIDRow, error) {
	rows, err := q.db.Query(ctx, listCommentsByDocumentID, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCommentsByDocumentIDRow
	for rows.Next() {
		var i ListCommentsByDocumentIDRow
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.AuthorUserID,
			&i.Body,
			&i.CreatedAt,
			&i.AuthorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
