// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: documents.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addCollectionMember = `-- name: AddCollectionMember :exec
INSERT INTO collection_members (collection_id, user_id, access_level)
VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type AddCollectionMemberParams struct {
	CollectionID pgtype.UUID `json:"collection_id"`
	UserID       pgtype.UUID `json:"user_id"`
	AccessLevel  string      `json:"access_level"`
}

func (q *Queries) AddCollectionMember(ctx context.Context, arg AddCollectionMemberParams) error {
	_, err := q.db.Exec(ctx, addCollectionMember, arg.CollectionID, arg.UserID, arg.AccessLevel)
	return err
}

const archiveDocument = `-- name: ArchiveDocument :exec
UPDATE documents
SET status = 'archived',
    archived_at = now(),
    updated_at = now()
WHERE id = $1
`

func (q *Queries) ArchiveDocument(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, archiveDocument, id)
	return err
}

const archiveExpiredDocuments = `-- name: ArchiveExpiredDocuments :exec
UPDATE documents
SET status = 'archived',
    archived_at = now(),
    updated_at = now()
WHERE org_id = $1
  AND deleted_at IS NULL
  AND status = 'ready'
  AND updated_at < $2
`

type ArchiveExpiredDocumentsParams struct {
	OrgID     pgtype.UUID        `json:"org_id"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ArchiveExpiredDocuments(ctx context.Context, arg ArchiveExpiredDocumentsParams) error {
	_, err := q.db.Exec(ctx, archiveExpiredDocuments, arg.OrgID, arg.UpdatedAt)
	return err
}

const attachTag = `-- name: AttachTag :exec
INSERT INTO document_tags (document_id, tag_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AttachTagParams struct {
	DocumentID pgtype.UUID `json:"document_id"`
	TagID      pgtype.UUID `json:"tag_id"`
}

func (q *Queries) AttachTag(ctx context.Context, arg AttachTagParams) error {
	_, err := q.db.Exec(ctx, attachTag, arg.DocumentID, arg.TagID)
	return err
}

const completeUpload = `-- name: CompleteUpload :exec
UPDATE uploads
SET status = $2,
    document_id = $3,
    completed_at = now()
WHERE id = $1
`

type CompleteUploadParams struct {
	ID         pgtype.UUID `json:"id"`
	Status     string      `json:"status"`
	DocumentID pgtype.UUID `json:"document_id"`
}

func (q *Queries) CompleteUpload(ctx context.Context, arg CompleteUploadParams) error {
	_, err := q.db.Exec(ctx, completeUpload, arg.ID, arg.Status, arg.DocumentID)
	return err
}

const countAccessibleDocuments = `-- name: CountAccessibleDocuments :one
SELECT count(DISTINCT d.id)
FROM documents d
WHERE d.org_id = $1
  AND d.deleted_at IS NULL
  AND (
    $4::boolean
    OR d.owner_user_id = $2
    OR EXISTS (
      SELECT 1 FROM users u WHERE u.id = $2 AND u.org_id = $1
    )
    OR EXISTS (
      SELECT 1
      FROM collection_members cm
      WHERE cm.collection_id = d.collection_id
        AND cm.user_id = $2
    )
    OR EXISTS (
      SELECT 1
      FROM document_permissions dp
      WHERE dp.document_id = d.id
        AND dp.allow = true
        AND (
          (dp.subject_type = 'user' AND dp.subject_id = $2)
          OR (dp.subject_type = 'role' AND dp.subject_id = ANY($3::uuid[]))
        )
    )
  )
  AND (
    $5::text = ''
    OR d.title ILIKE '%' || $5 || '%'
    OR d.original_filename ILIKE '%' || $5 || '%'
  )
`

type CountAccessibleDocumentsParams struct {
	OrgID       pgtype.UUID   `json:"org_id"`
	OwnerUserID pgtype.UUID   `json:"owner_user_id"`
	Column3     []pgtype.UUID `json:"column_3"`
	Column4     bool          `json:"column_4"`
	Column5     string        `json:"column_5"`
}

func (q *Queries) CountAccessibleDocuments(ctx context.Context, arg CountAccessibleDocumentsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAccessibleDocuments,
		arg.OrgID,
		arg.OwnerUserID,
		arg.Column3,
		arg.Column4,
		arg.Column5,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCollection = `-- name: CreateCollection :one
INSERT INTO collections (org_id, name, description, created_by)
VALUES ($1, $2, $3, $4)
RETURNING id, org_id, name, description, created_by, created_at, updated_at
`

type CreateCollectionParams struct {
	OrgID       pgtype.UUID `json:"org_id"`
	Name        string      `json:"name"`
	Description string      `json:"description"`
	CreatedBy   pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateCollection(ctx context.Context, arg CreateCollectionParams) (Collection, error) {
	row := q.db.QueryRow(ctx, createCollection,
		arg.OrgID,
		arg.Name,
		arg.Description,
		arg.CreatedBy,
	)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createDocument = `-- name: CreateDocument :one
INSERT INTO documents (
  id,
  org_id,
  title,
  original_filename,
  mime_type,
  size_bytes,
  checksum_sha256,
  owner_user_id,
  collection_id,
  status
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING id, org_id, title, original_filename, mime_type, size_bytes, checksum_sha256, owner_user_id, collection_id, current_version_id, status, archived_at, deleted_at, created_at, updated_at, search_vector
`

type CreateDocumentParams struct {
	ID               pgtype.UUID `json:"id"`
	OrgID            pgtype.UUID `json:"org_id"`
	Title            string      `json:"title"`
	OriginalFilename string      `json:"original_filename"`
	MimeType         string      `json:"mime_type"`
	SizeBytes        int64       `json:"size_bytes"`
	ChecksumSha256   string      `json:"checksum_sha256"`
	OwnerUserID      pgtype.UUID `json:"owner_user_id"`
	CollectionID     pgtype.UUID `json:"collection_id"`
	Status           string      `json:"status"`
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, createDocument,
		arg.ID,
		arg.OrgID,
		arg.Title,
		arg.OriginalFilename,
		arg.MimeType,
		arg.SizeBytes,
		arg.ChecksumSha256,
		arg.OwnerUserID,
		arg.CollectionID,
		arg.Status,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Title,
		&i.OriginalFilename,
		&i.MimeType,
		&i.SizeBytes,
		&i.ChecksumSha256,
		&i.OwnerUserID,
		&i.CollectionID,
		&i.CurrentVersionID,
		&i.Status,
		&i.ArchivedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SearchVector,
	)
	return i, err
}

const createDocumentVersion = `-- name: CreateDocumentVersion :one
INSERT INTO document_versions (
  id,
  document_id,
  version_number,
  storage_key,
  size_bytes,
  checksum_sha256,
  mime_type,
  uploaded_by,
  change_summary
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, document_id, version_number, storage_key, size_bytes, checksum_sha256, mime_type, uploaded_by, created_at, change_summary
`

type CreateDocumentVersionParams struct {
	ID             pgtype.UUID `json:"id"`
	DocumentID     pgtype.UUID `json:"document_id"`
	VersionNumber  int32       `json:"version_number"`
	StorageKey     string      `json:"storage_key"`
	SizeBytes      int64       `json:"size_bytes"`
	ChecksumSha256 string      `json:"checksum_sha256"`
	MimeType       string      `json:"mime_type"`
	UploadedBy     pgtype.UUID `json:"uploaded_by"`
	ChangeSummary  string      `json:"change_summary"`
}

func (q *Queries) CreateDocumentVersion(ctx context.Context, arg CreateDocumentVersionParams) (DocumentVersion, error) {
	row := q.db.QueryRow(ctx, createDocumentVersion,
		arg.ID,
		arg.DocumentID,
		arg.VersionNumber,
		arg.StorageKey,
		arg.SizeBytes,
		arg.ChecksumSha256,
		arg.MimeType,
		arg.UploadedBy,
		arg.ChangeSummary,
	)
	var i DocumentVersion
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.VersionNumber,
		&i.StorageKey,
		&i.SizeBytes,
		&i.ChecksumSha256,
		&i.MimeType,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.ChangeSummary,
	)
	return i, err
}

const createUpload = `-- name: CreateUpload :one
INSERT INTO uploads (
  org_id,
  user_id,
  object_key,
  original_filename,
  mime_type,
  size_bytes,
  checksum_sha256,
  status,
  expires_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, org_id, user_id, document_id, object_key, original_filename, mime_type, size_bytes, checksum_sha256, status, created_at, completed_at, expires_at
`

type CreateUploadParams struct {
	OrgID            pgtype.UUID        `json:"org_id"`
	UserID           pgtype.UUID        `json:"user_id"`
	ObjectKey        string             `json:"object_key"`
	OriginalFilename string             `json:"original_filename"`
	MimeType         string             `json:"mime_type"`
	SizeBytes        int64              `json:"size_bytes"`
	ChecksumSha256   string             `json:"checksum_sha256"`
	Status           string             `json:"status"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateUpload(ctx context.Context, arg CreateUploadParams) (Upload, error) {
	row := q.db.QueryRow(ctx, createUpload,
		arg.OrgID,
		arg.UserID,
		arg.ObjectKey,
		arg.OriginalFilename,
		arg.MimeType,
		arg.SizeBytes,
		arg.ChecksumSha256,
		arg.Status,
		arg.ExpiresAt,
	)
	var i Upload
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UserID,
		&i.DocumentID,
		&i.ObjectKey,
		&i.OriginalFilename,
		&i.MimeType,
		&i.SizeBytes,
		&i.ChecksumSha256,
		&i.Status,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteCollection = `-- name: DeleteCollection :exec
DELETE FROM collections
WHERE id = $1
`

func (q *Queries) DeleteCollection(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCollection, id)
	return err
}

const deleteDocumentTags = `-- name: DeleteDocumentTags :exec
DELETE FROM document_tags
WHERE document_id = $1
`

func (q *Queries) DeleteDocumentTags(ctx context.Context, documentID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteDocumentTags, documentID)
	return err
}

const deleteMetadataForDocument = `-- name: DeleteMetadataForDocument :exec
DELETE FROM document_metadata
WHERE document_id = $1
`

func (q *Queries) DeleteMetadataForDocument(ctx context.Context, documentID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteMetadataForDocument, documentID)
	return err
}

const deleteUpload = `-- name: DeleteUpload :exec
DELETE FROM uploads
WHERE id = $1
`

func (q *Queries) DeleteUpload(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUpload, id)
	return err
}

const getCollectionByID = `-- name: GetCollectionByID :one
SELECT id, org_id, name, description, created_by, created_at, updated_at FROM collections
WHERE id = $1
`

func (q *Queries) GetCollectionByID(ctx context.Context, id pgtype.UUID) (Collection, error) {
	row := q.db.QueryRow(ctx, getCollectionByID, id)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDocumentByID = `-- name: GetDocumentByID :one
SELECT id, org_id, title, original_filename, mime_type, size_bytes, checksum_sha256, owner_user_id, collection_id, current_version_id, status, archived_at, deleted_at, created_at, updated_at, search_vector FROM documents
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetDocumentByID(ctx context.Context, id pgtype.UUID) (Document, error) {
	row := q.db.QueryRow(ctx, getDocumentByID, id)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Title,
		&i.OriginalFilename,
		&i.MimeType,
		&i.SizeBytes,
		&i.ChecksumSha256,
		&i.OwnerUserID,
		&i.CollectionID,
		&i.CurrentVersionID,
		&i.Status,
		&i.ArchivedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SearchVector,
	)
	return i, err
}

const getDocumentByVersionID = `-- name: GetDocumentByVersionID :one
SELECT d.id, d.org_id, d.title, d.original_filename, d.mime_type, d.size_bytes, d.checksum_sha256, d.owner_user_id, d.collection_id, d.current_version_id, d.status, d.archived_at, d.deleted_at, d.created_at, d.updated_at, d.search_vector
FROM documents d
JOIN document_versions dv ON dv.document_id = d.id
WHERE dv.id = $1
  AND d.deleted_at IS NULL
`

func (q *Queries) GetDocumentByVersionID(ctx context.Context, id pgtype.UUID) (Document, error) {
	row := q.db.QueryRow(ctx, getDocumentByVersionID, id)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Title,
		&i.OriginalFilename,
		&i.MimeType,
		&i.SizeBytes,
		&i.ChecksumSha256,
		&i.OwnerUserID,
		&i.CollectionID,
		&i.CurrentVersionID,
		&i.Status,
		&i.ArchivedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SearchVector,
	)
	return i, err
}

const getDocumentVersionByID = `-- name: GetDocumentVersionByID :one
SELECT id, document_id, version_number, storage_key, size_bytes, checksum_sha256, mime_type, uploaded_by, created_at, change_summary FROM document_versions
WHERE id = $1
`

func (q *Queries) GetDocumentVersionByID(ctx context.Context, id pgtype.UUID) (DocumentVersion, error) {
	row := q.db.QueryRow(ctx, getDocumentVersionByID, id)
	var i DocumentVersion
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.VersionNumber,
		&i.StorageKey,
		&i.SizeBytes,
		&i.ChecksumSha256,
		&i.MimeType,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.ChangeSummary,
	)
	return i, err
}

const getLatestVersionNumber = `-- name: GetLatestVersionNumber :one
SELECT COALESCE(MAX(version_number), 0)::int4
FROM document_versions
WHERE document_id = $1
`

func (q *Queries) GetLatestVersionNumber(ctx context.Context, documentID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getLatestVersionNumber, documentID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const getOCRTextByVersionID = `-- name: GetOCRTextByVersionID :one
SELECT id, document_version_id, content, extraction_status, extracted_at, language, confidence_score, search_vector FROM ocr_text
WHERE document_version_id = $1
`

func (q *Queries) GetOCRTextByVersionID(ctx context.Context, documentVersionID pgtype.UUID) (OcrText, error) {
	row := q.db.QueryRow(ctx, getOCRTextByVersionID, documentVersionID)
	var i OcrText
	err := row.Scan(
		&i.ID,
		&i.DocumentVersionID,
		&i.Content,
		&i.ExtractionStatus,
		&i.ExtractedAt,
		&i.Language,
		&i.ConfidenceScore,
		&i.SearchVector,
	)
	return i, err
}

const getUploadByID = `-- name: GetUploadByID :one
SELECT id, org_id, user_id, document_id, object_key, original_filename, mime_type, size_bytes, checksum_sha256, status, created_at, completed_at, expires_at FROM uploads
WHERE id = $1
`

func (q *Queries) GetUploadByID(ctx context.Context, id pgtype.UUID) (Upload, error) {
	row := q.db.QueryRow(ctx, getUploadByID, id)
	var i Upload
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UserID,
		&i.DocumentID,
		&i.ObjectKey,
		&i.OriginalFilename,
		&i.MimeType,
		&i.SizeBytes,
		&i.ChecksumSha256,
		&i.Status,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const insertDocumentPermission = `-- name: InsertDocumentPermission :exec
INSERT INTO document_permissions (
  document_id,
  subject_type,
  subject_id,
  access_level,
  allow
) VALUES ($1, $2, $3, $4, $5)
`

type InsertDocumentPermissionParams struct {
	DocumentID  pgtype.UUID `json:"document_id"`
	SubjectType string      `json:"subject_type"`
	SubjectID   pgtype.UUID `json:"subject_id"`
	AccessLevel string      `json:"access_level"`
	Allow       bool        `json:"allow"`
}

func (q *Queries) InsertDocumentPermission(ctx context.Context, arg InsertDocumentPermissionParams) error {
	_, err := q.db.Exec(ctx, insertDocumentPermission,
		arg.DocumentID,
		arg.SubjectType,
		arg.SubjectID,
		arg.AccessLevel,
		arg.Allow,
	)
	return err
}

const insertMetadata = `-- name: InsertMetadata :exec
INSERT INTO document_metadata (
  document_id,
  schema_key,
  value_text,
  value_number,
  value_boolean,
  value_date,
  value_jsonb
) VALUES (
  $1, $2, $3, $4, $5, $6, $7
)
`

type InsertMetadataParams struct {
	DocumentID   pgtype.UUID    `json:"document_id"`
	SchemaKey    string         `json:"schema_key"`
	ValueText    pgtype.Text    `json:"value_text"`
	ValueNumber  pgtype.Numeric `json:"value_number"`
	ValueBoolean pgtype.Bool    `json:"value_boolean"`
	ValueDate    pgtype.Date    `json:"value_date"`
	ValueJsonb   []byte         `json:"value_jsonb"`
}

func (q *Queries) InsertMetadata(ctx context.Context, arg InsertMetadataParams) error {
	_, err := q.db.Exec(ctx, insertMetadata,
		arg.DocumentID,
		arg.SchemaKey,
		arg.ValueText,
		arg.ValueNumber,
		arg.ValueBoolean,
		arg.ValueDate,
		arg.ValueJsonb,
	)
	return err
}

const isCollectionMember = `-- name: IsCollectionMember :one
SELECT EXISTS (
  SELECT 1
  FROM collection_members
  WHERE collection_id = $1
    AND user_id = $2
)
`

type IsCollectionMemberParams struct {
	CollectionID pgtype.UUID `json:"collection_id"`
	UserID       pgtype.UUID `json:"user_id"`
}

func (q *Queries) IsCollectionMember(ctx context.Context, arg IsCollectionMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, isCollectionMember, arg.CollectionID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listAccessibleDocuments = `-- name: ListAccessibleDocuments :many
SELECT DISTINCT
  d.id, d.org_id, d.title, d.original_filename, d.mime_type, d.size_bytes, d.checksum_sha256, d.owner_user_id, d.collection_id, d.current_version_id, d.status, d.archived_at, d.deleted_at, d.created_at, d.updated_at, d.search_vector,
  dv.version_number AS current_version_number,
  COALESCE(pa.storage_key, '') AS preview_storage_key
FROM documents d
LEFT JOIN document_versions dv ON dv.id = d.current_version_id
LEFT JOIN preview_assets pa
  ON pa.document_version_id = d.current_version_id
 AND pa.asset_type = 'preview'
WHERE d.org_id = $1
  AND d.deleted_at IS NULL
  AND (
    $4::boolean
    OR d.owner_user_id = $2
    OR EXISTS (
      SELECT 1 FROM users u WHERE u.id = $2 AND u.org_id = $1
    )
    OR EXISTS (
      SELECT 1
      FROM collection_members cm
      WHERE cm.collection_id = d.collection_id
        AND cm.user_id = $2
    )
    OR EXISTS (
      SELECT 1
      FROM document_permissions dp
      WHERE dp.document_id = d.id
        AND dp.allow = true
        AND (
          (dp.subject_type = 'user' AND dp.subject_id = $2)
          OR (dp.subject_type = 'role' AND dp.subject_id = ANY($3::uuid[]))
        )
    )
  )
  AND (
    $5::text = ''
    OR d.title ILIKE '%' || $5 || '%'
    OR d.original_filename ILIKE '%' || $5 || '%'
  )
ORDER BY d.updated_at DESC
LIMIT $6 OFFSET $7
`

type ListAccessibleDocumentsParams struct {
	OrgID       pgtype.UUID   `json:"org_id"`
	OwnerUserID pgtype.UUID   `json:"owner_user_id"`
	Column3     []pgtype.UUID `json:"column_3"`
	Column4     bool          `json:"column_4"`
	Column5     string        `json:"column_5"`
	Limit       int32         `json:"limit"`
	Offset      int32         `json:"offset"`
}

type ListAccessibleDocumentsRow struct {
	ID                   pgtype.UUID        `json:"id"`
	OrgID                pgtype.UUID        `json:"org_id"`
	Title                string             `json:"title"`
	OriginalFilename     string             `json:"original_filename"`
	MimeType             string             `json:"mime_type"`
	SizeBytes            int64              `json:"size_bytes"`
	ChecksumSha256       string             `json:"checksum_sha256"`
	OwnerUserID          pgtype.UUID        `json:"owner_user_id"`
	CollectionID         pgtype.UUID        `json:"collection_id"`
	CurrentVersionID     pgtype.UUID        `json:"current_version_id"`
	Status               string             `json:"status"`
	ArchivedAt           pgtype.Timestamptz `json:"archived_at"`
	DeletedAt            pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	SearchVector         interface{}        `json:"search_vector"`
	CurrentVersionNumber pgtype.Int4        `json:"current_version_number"`
	PreviewStorageKey    string             `json:"preview_storage_key"`
}

func (q *Queries) ListAccessibleDocuments(ctx context.Context, arg ListAccessibleDocumentsParams) ([]ListAccessibleDocumentsRow, error) {
	rows, err := q.db.Query(ctx, listAccessibleDocuments,
		arg.OrgID,
		arg.OwnerUserID,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAccessibleDocumentsRow
	for rows.Next() {
		var i ListAccessibleDocumentsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Title,
			&i.OriginalFilename,
			&i.MimeType,
			&i.SizeBytes,
			&i.ChecksumSha256,
			&i.OwnerUserID,
			&i.CollectionID,
			&i.CurrentVersionID,
			&i.Status,
			&i.ArchivedAt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SearchVector,
			&i.CurrentVersionNumber,
			&i.PreviewStorageKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCollectionMembers = `-- name: ListCollectionMembers :many
SELECT cm.collection_id, cm.user_id, cm.access_level, cm.created_at, u.full_name, u.email
FROM collection_members cm
JOIN users u ON u.id = cm.user_id
WHERE cm.collection_id = $1
ORDER BY u.full_name
`

type ListCollectionMembersRow struct {
	CollectionID pgtype.UUID        `json:"collection_id"`
	UserID       pgtype.UUID        `json:"user_id"`
	AccessLevel  string             `json:"access_level"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	FullName     string             `json:"full_name"`
	Email        string             `json:"email"`
}

func (q *Queries) ListCollectionMembers(ctx context.Context, collectionID pgtype.UUID) ([]ListCollectionMembersRow, error) {
	rows, err := q.db.Query(ctx, listCollectionMembers, collectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCollectionMembersRow
	for rows.Next() {
		var i ListCollectionMembersRow
		if err := rows.Scan(
			&i.CollectionID,
			&i.UserID,
			&i.AccessLevel,
			&i.CreatedAt,
			&i.FullName,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCollections = `-- name: ListCollections :many
SELECT id, org_id, name, description, created_by, created_at, updated_at FROM collections
WHERE org_id = $1
ORDER BY name
`

func (q *Queries) ListCollections(ctx context.Context, orgID pgtype.UUID) ([]Collection, error) {
	rows, err := q.db.Query(ctx, listCollections, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Collection
	for rows.Next() {
		var i Collection
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Description,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentPermissions = `-- name: ListDocumentPermissions :many
SELECT id, document_id, subject_type, subject_id, access_level, allow, created_at FROM document_permissions
WHERE document_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListDocumentPermissions(ctx context.Context, documentID pgtype.UUID) ([]DocumentPermission, error) {
	rows, err := q.db.Query(ctx, listDocumentPermissions, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DocumentPermission
	for rows.Next() {
		var i DocumentPermission
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.SubjectType,
			&i.SubjectID,
			&i.AccessLevel,
			&i.Allow,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentVersions = `-- name: ListDocumentVersions :many
SELECT id, document_id, version_number, storage_key, size_bytes, checksum_sha256, mime_type, uploaded_by, created_at, change_summary FROM document_versions
WHERE document_id = $1
ORDER BY version_number DESC
`

func (q *Queries) ListDocumentVersions(ctx context.Context, documentID pgtype.UUID) ([]DocumentVersion, error) {
	rows, err := q.db.Query(ctx, listDocumentVersions, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DocumentVersion
	for rows.Next() {
		var i DocumentVersion
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.VersionNumber,
			&i.StorageKey,
			&i.SizeBytes,
			&i.ChecksumSha256,
			&i.MimeType,
			&i.UploadedBy,
			&i.CreatedAt,
			&i.ChangeSummary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentsByCollectionID = `-- name: ListDocumentsByCollectionID :many
SELECT d.id, d.org_id, d.title, d.original_filename, d.mime_type, d.size_bytes, d.checksum_sha256, d.owner_user_id, d.collection_id, d.current_version_id, d.status, d.archived_at, d.deleted_at, d.created_at, d.updated_at, d.search_vector, dv.version_number AS current_version_number
FROM documents d
LEFT JOIN document_versions dv ON dv.id = d.current_version_id
WHERE d.collection_id = $1
  AND d.deleted_at IS NULL
ORDER BY d.updated_at DESC
LIMIT $2 OFFSET $3
`

type ListDocumentsByCollectionIDParams struct {
	CollectionID pgtype.UUID `json:"collection_id"`
	Limit        int32       `json:"limit"`
	Offset       int32       `json:"offset"`
}

type ListDocumentsByCollectionIDRow struct {
	ID                   pgtype.UUID        `json:"id"`
	OrgID                pgtype.UUID        `json:"org_id"`
	Title                string             `json:"title"`
	OriginalFilename     string             `json:"original_filename"`
	MimeType             string             `json:"mime_type"`
	SizeBytes            int64              `json:"size_bytes"`
	ChecksumSha256       string             `json:"checksum_sha256"`
	OwnerUserID          pgtype.UUID        `json:"owner_user_id"`
	CollectionID         pgtype.UUID        `json:"collection_id"`
	CurrentVersionID     pgtype.UUID        `json:"current_version_id"`
	Status               string             `json:"status"`
	ArchivedAt           pgtype.Timestamptz `json:"archived_at"`
	DeletedAt            pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	SearchVector         interface{}        `json:"search_vector"`
	CurrentVersionNumber pgtype.Int4        `json:"current_version_number"`
}

func (q *Queries) ListDocumentsByCollectionID(ctx context.Context, arg ListDocumentsByCollectionIDParams) ([]ListDocumentsByCollectionIDRow, error) {
	rows, err := q.db.Query(ctx, listDocumentsByCollectionID, arg.CollectionID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDocumentsByCollectionIDRow
	for rows.Next() {
		var i ListDocumentsByCollectionIDRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Title,
			&i.OriginalFilename,
			&i.MimeType,
			&i.SizeBytes,
			&i.ChecksumSha256,
			&i.OwnerUserID,
			&i.CollectionID,
			&i.CurrentVersionID,
			&i.Status,
			&i.ArchivedAt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SearchVector,
			&i.CurrentVersionNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMetadataByDocumentID = `-- name: ListMetadataByDocumentID :many
SELECT id, document_id, schema_key, value_text, value_number, value_boolean, value_date, value_jsonb, created_at FROM document_metadata
WHERE document_id = $1
ORDER BY schema_key
`

func (q *Queries) ListMetadataByDocumentID(ctx context.Context, documentID pgtype.UUID) ([]DocumentMetadatum, error) {
	rows, err := q.db.Query(ctx, listMetadataByDocumentID, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DocumentMetadatum
	for rows.Next() {
		var i DocumentMetadatum
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.SchemaKey,
			&i.ValueText,
			&i.ValueNumber,
			&i.ValueBoolean,
			&i.ValueDate,
			&i.ValueJsonb,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrphanUploads = `-- name: ListOrphanUploads :many
SELECT id, org_id, user_id, document_id, object_key, original_filename, mime_type, size_bytes, checksum_sha256, status, created_at, completed_at, expires_at FROM uploads
WHERE status = 'pending'
  AND expires_at < now()
ORDER BY created_at ASC
LIMIT $1
`

func (q *Queries) ListOrphanUploads(ctx context.Context, limit int32) ([]Upload, error) {
	rows, err := q.db.Query(ctx, listOrphanUploads, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Upload
	for rows.Next() {
		var i Upload
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.UserID,
			&i.DocumentID,
			&i.ObjectKey,
			&i.OriginalFilename,
			&i.MimeType,
			&i.SizeBytes,
			&i.ChecksumSha256,
			&i.Status,
			&i.CreatedAt,
			&i.CompletedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPreviewAssetsByVersionID = `-- name: ListPreviewAssetsByVersionID :many
SELECT id, document_version_id, asset_type, storage_key, status, created_at FROM preview_assets
WHERE document_version_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListPreviewAssetsByVersionID(ctx context.Context, documentVersionID pgtype.UUID) ([]PreviewAsset, error) {
	rows, err := q.db.Query(ctx, listPreviewAssetsByVersionID, documentVersionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PreviewAsset
	for rows.Next() {
		var i PreviewAsset
		if err := rows.Scan(
			&i.ID,
			&i.DocumentVersionID,
			&i.AssetType,
			&i.StorageKey,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSharedDocuments = `-- name: ListSharedDocuments :many
SELECT DISTINCT d.id, d.org_id, d.title, d.original_filename, d.mime_type, d.size_bytes, d.checksum_sha256, d.owner_user_id, d.collection_id, d.current_version_id, d.status, d.archived_at, d.deleted_at, d.created_at, d.updated_at, d.search_vector, dv.version_number AS current_version_number
FROM documents d
JOIN document_permissions dp ON dp.document_id = d.id
LEFT JOIN document_versions dv ON dv.id = d.current_version_id
WHERE dp.subject_type = 'user'
  AND dp.subject_id = $1
  AND dp.allow = true
  AND d.deleted_at IS NULL
ORDER BY d.updated_at DESC
LIMIT $2 OFFSET $3
`

type ListSharedDocumentsParams struct {
	SubjectID pgtype.UUID `json:"subject_id"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

type ListSharedDocumentsRow struct {
	ID                   pgtype.UUID        `json:"id"`
	OrgID                pgtype.UUID        `json:"org_id"`
	Title                string             `json:"title"`
	OriginalFilename     string             `json:"original_filename"`
	MimeType             string             `json:"mime_type"`
	SizeBytes            int64              `json:"size_bytes"`
	ChecksumSha256       string             `json:"checksum_sha256"`
	OwnerUserID          pgtype.UUID        `json:"owner_user_id"`
	CollectionID         pgtype.UUID        `json:"collection_id"`
	CurrentVersionID     pgtype.UUID        `json:"current_version_id"`
	Status               string             `json:"status"`
	ArchivedAt           pgtype.Timestamptz `json:"archived_at"`
	DeletedAt            pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	SearchVector         interface{}        `json:"search_vector"`
	CurrentVersionNumber pgtype.Int4        `json:"current_version_number"`
}

func (q *Queries) ListSharedDocuments(ctx context.Context, arg ListSharedDocumentsParams) ([]ListSharedDocumentsRow, error) {
	rows, err := q.db.Query(ctx, listSharedDocuments, arg.SubjectID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSharedDocumentsRow
	for rows.Next() {
		var i ListSharedDocumentsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Title,
			&i.OriginalFilename,
			&i.MimeType,
			&i.SizeBytes,
			&i.ChecksumSha256,
			&i.OwnerUserID,
			&i.CollectionID,
			&i.CurrentVersionID,
			&i.Status,
			&i.ArchivedAt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SearchVector,
			&i.CurrentVersionNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsByDocumentID = `-- name: ListTagsByDocumentID :many
SELECT t.id, t.org_id, t.name, t.color, t.created_at
FROM tags t
JOIN document_tags dt ON dt.tag_id = t.id
WHERE dt.document_id = $1
ORDER BY t.name
`

func (q *Queries) ListTagsByDocumentID(ctx context.Context, documentID pgtype.UUID) ([]Tag, error) {
	rows, err := q.db.Query(ctx, listTagsByDocumentID, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Color,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeCollectionMember = `-- name: RemoveCollectionMember :exec
DELETE FROM collection_members
WHERE collection_id = $1
  AND user_id = $2
`

type RemoveCollectionMemberParams struct {
	CollectionID pgtype.UUID `json:"collection_id"`
	UserID       pgtype.UUID `json:"user_id"`
}

func (q *Queries) RemoveCollectionMember(ctx context.Context, arg RemoveCollectionMemberParams) error {
	_, err := q.db.Exec(ctx, removeCollectionMember, arg.CollectionID, arg.UserID)
	return err
}

const restoreDocument = `-- name: RestoreDocument :exec
UPDATE documents
SET status = 'ready',
    archived_at = NULL,
    updated_at = now()
WHERE id = $1
`

func (q *Queries) RestoreDocument(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, restoreDocument, id)
	return err
}

const revokeDocumentShare = `-- name: RevokeDocumentShare :exec
DELETE FROM document_permissions
WHERE document_id = $1
  AND subject_type = $2
  AND subject_id = $3
`

type RevokeDocumentShareParams struct {
	DocumentID  pgtype.UUID `json:"document_id"`
	SubjectType string      `json:"subject_type"`
	SubjectID   pgtype.UUID `json:"subject_id"`
}

func (q *Queries) RevokeDocumentShare(ctx context.Context, arg RevokeDocumentShareParams) error {
	_, err := q.db.Exec(ctx, revokeDocumentShare, arg.DocumentID, arg.SubjectType, arg.SubjectID)
	return err
}

const setDocumentCurrentVersion = `-- name: SetDocumentCurrentVersion :exec
UPDATE documents
SET current_version_id = $2,
    size_bytes = $3,
    mime_type = $4,
    checksum_sha256 = $5,
    updated_at = now()
WHERE id = $1
`

type SetDocumentCurrentVersionParams struct {
	ID               pgtype.UUID `json:"id"`
	CurrentVersionID pgtype.UUID `json:"current_version_id"`
	SizeBytes        int64       `json:"size_bytes"`
	MimeType         string      `json:"mime_type"`
	ChecksumSha256   string      `json:"checksum_sha256"`
}

func (q *Queries) SetDocumentCurrentVersion(ctx context.Context, arg SetDocumentCurrentVersionParams) error {
	_, err := q.db.Exec(ctx, setDocumentCurrentVersion,
		arg.ID,
		arg.CurrentVersionID,
		arg.SizeBytes,
		arg.MimeType,
		arg.ChecksumSha256,
	)
	return err
}

const setDocumentStatus = `-- name: SetDocumentStatus :exec
UPDATE documents
SET status = $2,
    updated_at = now()
WHERE id = $1
`

type SetDocumentStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) SetDocumentStatus(ctx context.Context, arg SetDocumentStatusParams) error {
	_, err := q.db.Exec(ctx, setDocumentStatus, arg.ID, arg.Status)
	return err
}

const shareDocument = `-- name: ShareDocument :exec
INSERT INTO document_permissions (document_id, subject_type, subject_id, access_level, allow)
VALUES ($1, $2, $3, $4, true)
ON CONFLICT DO NOTHING
`

type ShareDocumentParams struct {
	DocumentID  pgtype.UUID `json:"document_id"`
	SubjectType string      `json:"subject_type"`
	SubjectID   pgtype.UUID `json:"subject_id"`
	AccessLevel string      `json:"access_level"`
}

func (q *Queries) ShareDocument(ctx context.Context, arg ShareDocumentParams) error {
	_, err := q.db.Exec(ctx, shareDocument,
		arg.DocumentID,
		arg.SubjectType,
		arg.SubjectID,
		arg.AccessLevel,
	)
	return err
}

const softDeleteDocument = `-- name: SoftDeleteDocument :exec
UPDATE documents
SET status = 'deleted',
    deleted_at = now(),
    updated_at = now()
WHERE id = $1
`

func (q *Queries) SoftDeleteDocument(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteDocument, id)
	return err
}

const updateCollection = `-- name: UpdateCollection :one
UPDATE collections
SET name = $2,
    description = $3,
    updated_at = now()
WHERE id = $1
RETURNING id, org_id, name, description, created_by, created_at, updated_at
`

type UpdateCollectionParams struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	Description string      `json:"description"`
}

func (q *Queries) UpdateCollection(ctx context.Context, arg UpdateCollectionParams) (Collection, error) {
	row := q.db.QueryRow(ctx, updateCollection, arg.ID, arg.Name, arg.Description)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDocumentCore = `-- name: UpdateDocumentCore :one
UPDATE documents
SET title = $2,
    collection_id = $3,
    status = $4,
    updated_at = now()
WHERE id = $1
RETURNING id, org_id, title, original_filename, mime_type, size_bytes, checksum_sha256, owner_user_id, collection_id, current_version_id, status, archived_at, deleted_at, created_at, updated_at, search_vector
`

type UpdateDocumentCoreParams struct {
	ID           pgtype.UUID `json:"id"`
	Title        string      `json:"title"`
	CollectionID pgtype.UUID `json:"collection_id"`
	Status       string      `json:"status"`
}

func (q *Queries) UpdateDocumentCore(ctx context.Context, arg UpdateDocumentCoreParams) (Document, error) {
	row := q.db.QueryRow(ctx, updateDocumentCore,
		arg.ID,
		arg.Title,
		arg.CollectionID,
		arg.Status,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Title,
		&i.OriginalFilename,
		&i.MimeType,
		&i.SizeBytes,
		&i.ChecksumSha256,
		&i.OwnerUserID,
		&i.CollectionID,
		&i.CurrentVersionID,
		&i.Status,
		&i.ArchivedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SearchVector,
	)
	return i, err
}

const upsertOCRText = `-- name: UpsertOCRText :one
INSERT INTO ocr_text (
  document_version_id,
  content,
  extraction_status,
  extracted_at,
  language,
  confidence_score
) VALUES (
  $1, $2, $3, $4, $5, $6
)
ON CONFLICT (document_version_id)
DO UPDATE SET
  content = EXCLUDED.content,
  extraction_status = EXCLUDED.extraction_status,
  extracted_at = EXCLUDED.extracted_at,
  language = EXCLUDED.language,
  confidence_score = EXCLUDED.confidence_score
RETURNING id, document_version_id, content, extraction_status, extracted_at, language, confidence_score, search_vector
`

type UpsertOCRTextParams struct {
	DocumentVersionID pgtype.UUID        `json:"document_version_id"`
	Content           string             `json:"content"`
	ExtractionStatus  string             `json:"extraction_status"`
	ExtractedAt       pgtype.Timestamptz `json:"extracted_at"`
	Language          string             `json:"language"`
	ConfidenceScore   pgtype.Numeric     `json:"confidence_score"`
}

func (q *Queries) UpsertOCRText(ctx context.Context, arg UpsertOCRTextParams) (OcrText, error) {
	row := q.db.QueryRow(ctx, upsertOCRText,
		arg.DocumentVersionID,
		arg.Content,
		arg.ExtractionStatus,
		arg.ExtractedAt,
		arg.Language,
		arg.ConfidenceScore,
	)
	var i OcrText
	err := row.Scan(
		&i.ID,
		&i.DocumentVersionID,
		&i.Content,
		&i.ExtractionStatus,
		&i.ExtractedAt,
		&i.Language,
		&i.ConfidenceScore,
		&i.SearchVector,
	)
	return i, err
}

const upsertPreviewAsset = `-- name: UpsertPreviewAsset :exec
INSERT INTO preview_assets (
  document_version_id,
  asset_type,
  storage_key,
  status
) VALUES ($1, $2, $3, $4)
ON CONFLICT DO NOTHING
`

type UpsertPreviewAssetParams struct {
	DocumentVersionID pgtype.UUID `json:"document_version_id"`
	AssetType         string      `json:"asset_type"`
	StorageKey        string      `json:"storage_key"`
	Status            string      `json:"status"`
}

func (q *Queries) UpsertPreviewAsset(ctx context.Context, arg UpsertPreviewAssetParams) error {
	_, err := q.db.Exec(ctx, upsertPreviewAsset,
		arg.DocumentVersionID,
		arg.AssetType,
		arg.StorageKey,
		arg.Status,
	)
	return err
}

const upsertTag = `-- name: UpsertTag :one
INSERT INTO tags (org_id, name, color)
VALUES ($1, $2, $3)
ON CONFLICT (org_id, name)
DO UPDATE SET color = EXCLUDED.color
RETURNING id, org_id, name, color, created_at
`

type UpsertTagParams struct {
	OrgID pgtype.UUID `json:"org_id"`
	Name  string      `json:"name"`
	Color string      `json:"color"`
}

func (q *Queries) UpsertTag(ctx context.Context, arg UpsertTagParams) (Tag, error) {
	row := q.db.QueryRow(ctx, upsertTag, arg.OrgID, arg.Name, arg.Color)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
	)
	return i, err
}
