// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type AuditEvent struct {
	ID           pgtype.UUID        `json:"id"`
	OrgID        pgtype.UUID        `json:"org_id"`
	ActorUserID  pgtype.UUID        `json:"actor_user_id"`
	ActorRole    string             `json:"actor_role"`
	Action       string             `json:"action"`
	ResourceType string             `json:"resource_type"`
	ResourceID   pgtype.UUID        `json:"resource_id"`
	IpAddress    *netip.Addr        `json:"ip_address"`
	UserAgent    string             `json:"user_agent"`
	RequestID    string             `json:"request_id"`
	PayloadJson  []byte             `json:"payload_json"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Collection struct {
	ID          pgtype.UUID        `json:"id"`
	OrgID       pgtype.UUID        `json:"org_id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type CollectionMember struct {
	CollectionID pgtype.UUID        `json:"collection_id"`
	UserID       pgtype.UUID        `json:"user_id"`
	AccessLevel  string             `json:"access_level"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Comment struct {
	ID           pgtype.UUID        `json:"id"`
	DocumentID   pgtype.UUID        `json:"document_id"`
	AuthorUserID pgtype.UUID        `json:"author_user_id"`
	Body         string             `json:"body"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Document struct {
	ID               pgtype.UUID        `json:"id"`
	OrgID            pgtype.UUID        `json:"org_id"`
	Title            string             `json:"title"`
	OriginalFilename string             `json:"original_filename"`
	MimeType         string             `json:"mime_type"`
	SizeBytes        int64              `json:"size_bytes"`
	ChecksumSha256   string             `json:"checksum_sha256"`
	OwnerUserID      pgtype.UUID        `json:"owner_user_id"`
	CollectionID     pgtype.UUID        `json:"collection_id"`
	CurrentVersionID pgtype.UUID        `json:"current_version_id"`
	Status           string             `json:"status"`
	ArchivedAt       pgtype.Timestamptz `json:"archived_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	SearchVector     interface{}        `json:"search_vector"`
}

type DocumentMetadatum struct {
	ID           pgtype.UUID        `json:"id"`
	DocumentID   pgtype.UUID        `json:"document_id"`
	SchemaKey    string             `json:"schema_key"`
	ValueText    pgtype.Text        `json:"value_text"`
	ValueNumber  pgtype.Numeric     `json:"value_number"`
	ValueBoolean pgtype.Bool        `json:"value_boolean"`
	ValueDate    pgtype.Date        `json:"value_date"`
	ValueJsonb   []byte             `json:"value_jsonb"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type DocumentPermission struct {
	ID          pgtype.UUID        `json:"id"`
	DocumentID  pgtype.UUID        `json:"document_id"`
	SubjectType string             `json:"subject_type"`
	SubjectID   pgtype.UUID        `json:"subject_id"`
	AccessLevel string             `json:"access_level"`
	Allow       bool               `json:"allow"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type DocumentTag struct {
	DocumentID pgtype.UUID `json:"document_id"`
	TagID      pgtype.UUID `json:"tag_id"`
}

type DocumentVersion struct {
	ID             pgtype.UUID        `json:"id"`
	DocumentID     pgtype.UUID        `json:"document_id"`
	VersionNumber  int32              `json:"version_number"`
	StorageKey     string             `json:"storage_key"`
	SizeBytes      int64              `json:"size_bytes"`
	ChecksumSha256 string             `json:"checksum_sha256"`
	MimeType       string             `json:"mime_type"`
	UploadedBy     pgtype.UUID        `json:"uploaded_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	ChangeSummary  string             `json:"change_summary"`
}

type Notification struct {
	ID          pgtype.UUID        `json:"id"`
	OrgID       pgtype.UUID        `json:"org_id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Kind        string             `json:"kind"`
	Title       string             `json:"title"`
	Body        string             `json:"body"`
	PayloadJson []byte             `json:"payload_json"`
	ReadAt      pgtype.Timestamptz `json:"read_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type OcrJob struct {
	ID                pgtype.UUID        `json:"id"`
	DocumentVersionID pgtype.UUID        `json:"document_version_id"`
	JobType           string             `json:"job_type"`
	TaskID            string             `json:"task_id"`
	Status            string             `json:"status"`
	PayloadJson       []byte             `json:"payload_json"`
	AttemptCount      int32              `json:"attempt_count"`
	ErrorMessage      pgtype.Text        `json:"error_message"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	FinishedAt        pgtype.Timestamptz `json:"finished_at"`
}

type OcrText struct {
	ID                pgtype.UUID        `json:"id"`
	DocumentVersionID pgtype.UUID        `json:"document_version_id"`
	Content           string             `json:"content"`
	ExtractionStatus  string             `json:"extraction_status"`
	ExtractedAt       pgtype.Timestamptz `json:"extracted_at"`
	Language          string             `json:"language"`
	ConfidenceScore   pgtype.Numeric     `json:"confidence_score"`
	SearchVector      interface{}        `json:"search_vector"`
}

type Organization struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Slug      string             `json:"slug"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Permission struct {
	ID          pgtype.UUID `json:"id"`
	Key         string      `json:"key"`
	Description string      `json:"description"`
}

type PreviewAsset struct {
	ID                pgtype.UUID        `json:"id"`
	DocumentVersionID pgtype.UUID        `json:"document_version_id"`
	AssetType         string             `json:"asset_type"`
	StorageKey        string             `json:"storage_key"`
	Status            string             `json:"status"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type Quota struct {
	ID               pgtype.UUID        `json:"id"`
	OrgID            pgtype.UUID        `json:"org_id"`
	TargetType       string             `json:"target_type"`
	TargetID         pgtype.UUID        `json:"target_id"`
	MaxStorageBytes  int64              `json:"max_storage_bytes"`
	MaxDocumentCount int32              `json:"max_document_count"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type RetentionPolicy struct {
	ID                    pgtype.UUID        `json:"id"`
	OrgID                 pgtype.UUID        `json:"org_id"`
	Name                  string             `json:"name"`
	AppliesToCollectionID pgtype.UUID        `json:"applies_to_collection_id"`
	RetentionDays         int32              `json:"retention_days"`
	ArchiveAfterDays      pgtype.Int4        `json:"archive_after_days"`
	DeleteAfterDays       pgtype.Int4        `json:"delete_after_days"`
	Enabled               bool               `json:"enabled"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

type Role struct {
	ID          pgtype.UUID        `json:"id"`
	OrgID       pgtype.UUID        `json:"org_id"`
	Key         string             `json:"key"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type RolePermission struct {
	RoleID       pgtype.UUID `json:"role_id"`
	PermissionID pgtype.UUID `json:"permission_id"`
}

type SavedSearch struct {
	ID          pgtype.UUID        `json:"id"`
	OrgID       pgtype.UUID        `json:"org_id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Name        string             `json:"name"`
	QueryText   string             `json:"query_text"`
	FiltersJson []byte             `json:"filters_json"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type SystemSetting struct {
	ID           pgtype.UUID        `json:"id"`
	OrgID        pgtype.UUID        `json:"org_id"`
	SettingKey   string             `json:"setting_key"`
	SettingValue []byte             `json:"setting_value"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Tag struct {
	ID        pgtype.UUID        `json:"id"`
	OrgID     pgtype.UUID        `json:"org_id"`
	Name      string             `json:"name"`
	Color     string             `json:"color"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type TeamInvite struct {
	ID        pgtype.UUID        `json:"id"`
	OrgID     pgtype.UUID        `json:"org_id"`
	Code      string             `json:"code"`
	CreatedBy pgtype.UUID        `json:"created_by"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	MaxUses   int32              `json:"max_uses"`
	UseCount  int32              `json:"use_count"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Upload struct {
	ID               pgtype.UUID        `json:"id"`
	OrgID            pgtype.UUID        `json:"org_id"`
	UserID           pgtype.UUID        `json:"user_id"`
	DocumentID       pgtype.UUID        `json:"document_id"`
	ObjectKey        string             `json:"object_key"`
	OriginalFilename string             `json:"original_filename"`
	MimeType         string             `json:"mime_type"`
	SizeBytes        int64              `json:"size_bytes"`
	ChecksumSha256   string             `json:"checksum_sha256"`
	Status           string             `json:"status"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	CompletedAt      pgtype.Timestamptz `json:"completed_at"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
}

type User struct {
	ID                  pgtype.UUID        `json:"id"`
	OrgID               pgtype.UUID        `json:"org_id"`
	Email               string             `json:"email"`
	FullName            string             `json:"full_name"`
	PasswordHash        string             `json:"password_hash"`
	MfaEnabled          bool               `json:"mfa_enabled"`
	MfaSecretEncrypted  []byte             `json:"mfa_secret_encrypted"`
	Status              string             `json:"status"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	LastLoginAt         pgtype.Timestamptz `json:"last_login_at"`
	FailedLoginAttempts int32              `json:"failed_login_attempts"`
	LockedUntil         pgtype.Timestamptz `json:"locked_until"`
	GoogleID            pgtype.Text        `json:"google_id"`
	AvatarUrl           string             `json:"avatar_url"`
}

type UserRole struct {
	UserID pgtype.UUID `json:"user_id"`
	RoleID pgtype.UUID `json:"role_id"`
}
