// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notifications.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (
  org_id,
  user_id,
  kind,
  title,
  body,
  payload_json
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, org_id, user_id, kind, title, body, payload_json, read_at, created_at
`

type CreateNotificationParams struct {
	OrgID       pgtype.UUID `json:"org_id"`
	UserID      pgtype.UUID `json:"user_id"`
	Kind        string      `json:"kind"`
	Title       string      `json:"title"`
	Body        string      `json:"body"`
	PayloadJson []byte      `json:"payload_json"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.OrgID,
		arg.UserID,
		arg.Kind,
		arg.Title,
		arg.Body,
		arg.PayloadJson,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UserID,
		&i.Kind,
		&i.Title,
		&i.Body,
		&i.PayloadJson,
		&i.ReadAt,
		&i.CreatedAt,
	)
	return i, err
}

const listNotificationsByUserID = `-- name: ListNotificationsByUserID :many
SELECT id, org_id, user_id, kind, title, body, payload_json, read_at, created_at FROM notifications
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListNotificationsByUserIDParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
}

func (q *Queries) ListNotificationsByUserID(ctx context.Context, arg ListNotificationsByUserIDParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotificationsByUserID, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.UserID,
			&i.Kind,
			&i.Title,
			&i.Body,
			&i.PayloadJson,
			&i.ReadAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNotificationRead = `-- name: MarkNotificationRead :exec
UPDATE notifications
SET read_at = now()
WHERE id = $1
  AND user_id = $2
`

type MarkNotificationReadParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) error {
	_, err := q.db.Exec(ctx, markNotificationRead, arg.ID, arg.UserID)
	return err
}
