// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddCollectionMember(ctx context.Context, arg AddCollectionMemberParams) error
	AddUserRole(ctx context.Context, arg AddUserRoleParams) error
	ArchiveDocument(ctx context.Context, id pgtype.UUID) error
	ArchiveExpiredDocuments(ctx context.Context, arg ArchiveExpiredDocumentsParams) error
	AttachTag(ctx context.Context, arg AttachTagParams) error
	CompleteUpload(ctx context.Context, arg CompleteUploadParams) error
	CountAccessibleDocuments(ctx context.Context, arg CountAccessibleDocumentsParams) (int64, error)
	CreateCollection(ctx context.Context, arg CreateCollectionParams) (Collection, error)
	CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error)
	CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error)
	CreateDocumentVersion(ctx context.Context, arg CreateDocumentVersionParams) (DocumentVersion, error)
	CreateJob(ctx context.Context, arg CreateJobParams) (OcrJob, error)
	CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error)
	CreateSavedSearch(ctx context.Context, arg CreateSavedSearchParams) (SavedSearch, error)
	CreateUpload(ctx context.Context, arg CreateUploadParams) (Upload, error)
	DeleteCollection(ctx context.Context, id pgtype.UUID) error
	DeleteDocumentTags(ctx context.Context, documentID pgtype.UUID) error
	DeleteMetadataForDocument(ctx context.Context, documentID pgtype.UUID) error
	DeleteSavedSearch(ctx context.Context, arg DeleteSavedSearchParams) error
	DeleteUpload(ctx context.Context, id pgtype.UUID) error
	DeleteUserRolesByUserID(ctx context.Context, userID pgtype.UUID) error
	GetCollectionByID(ctx context.Context, id pgtype.UUID) (Collection, error)
	GetDocumentByID(ctx context.Context, id pgtype.UUID) (Document, error)
	GetDocumentByVersionID(ctx context.Context, id pgtype.UUID) (Document, error)
	GetDocumentVersionByID(ctx context.Context, id pgtype.UUID) (DocumentVersion, error)
	GetJobByID(ctx context.Context, id pgtype.UUID) (OcrJob, error)
	GetLatestVersionNumber(ctx context.Context, documentID pgtype.UUID) (int32, error)
	GetOCRTextByVersionID(ctx context.Context, documentVersionID pgtype.UUID) (OcrText, error)
	GetUploadByID(ctx context.Context, id pgtype.UUID) (Upload, error)
	GetUsageSummary(ctx context.Context, orgID pgtype.UUID) (GetUsageSummaryRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	IncrementFailedLoginAttempts(ctx context.Context, id pgtype.UUID) error
	InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) (AuditEvent, error)
	InsertDocumentPermission(ctx context.Context, arg InsertDocumentPermissionParams) error
	InsertMetadata(ctx context.Context, arg InsertMetadataParams) error
	IsCollectionMember(ctx context.Context, arg IsCollectionMemberParams) (bool, error)
	ListAccessibleDocuments(ctx context.Context, arg ListAccessibleDocumentsParams) ([]ListAccessibleDocumentsRow, error)
	ListAuditEvents(ctx context.Context, arg ListAuditEventsParams) ([]AuditEvent, error)
	ListAuditEventsFiltered(ctx context.Context, arg ListAuditEventsFilteredParams) ([]AuditEvent, error)
	ListCollectionMembers(ctx context.Context, collectionID pgtype.UUID) ([]ListCollectionMembersRow, error)
	ListCollections(ctx context.Context, orgID pgtype.UUID) ([]Collection, error)
	ListCommentsByDocumentID(ctx context.Context, documentID pgtype.UUID) ([]ListCommentsByDocumentIDRow, error)
	ListDocumentPermissions(ctx context.Context, documentID pgtype.UUID) ([]DocumentPermission, error)
	ListDocumentVersions(ctx context.Context, documentID pgtype.UUID) ([]DocumentVersion, error)
	ListDocumentsByCollectionID(ctx context.Context, arg ListDocumentsByCollectionIDParams) ([]ListDocumentsByCollectionIDRow, error)
	ListJobs(ctx context.Context, limit int32) ([]OcrJob, error)
	ListMetadataByDocumentID(ctx context.Context, documentID pgtype.UUID) ([]DocumentMetadatum, error)
	ListNotificationsByUserID(ctx context.Context, arg ListNotificationsByUserIDParams) ([]Notification, error)
	ListOrganizations(ctx context.Context) ([]Organization, error)
	ListOrphanUploads(ctx context.Context, limit int32) ([]Upload, error)
	ListPermissionsByRoleIDs(ctx context.Context, dollar_1 []pgtype.UUID) ([]Permission, error)
	ListPreviewAssetsByVersionID(ctx context.Context, documentVersionID pgtype.UUID) ([]PreviewAsset, error)
	ListQuotas(ctx context.Context, orgID pgtype.UUID) ([]Quota, error)
	ListRetentionPolicies(ctx context.Context, orgID pgtype.UUID) ([]RetentionPolicy, error)
	ListRoles(ctx context.Context, orgID pgtype.UUID) ([]Role, error)
	ListSavedSearches(ctx context.Context, userID pgtype.UUID) ([]SavedSearch, error)
	ListSharedDocuments(ctx context.Context, arg ListSharedDocumentsParams) ([]ListSharedDocumentsRow, error)
	ListSystemSettings(ctx context.Context, orgID pgtype.UUID) ([]SystemSetting, error)
	ListTagsByDocumentID(ctx context.Context, documentID pgtype.UUID) ([]Tag, error)
	ListUserRoles(ctx context.Context, userID pgtype.UUID) ([]Role, error)
	ListUsers(ctx context.Context, orgID pgtype.UUID) ([]ListUsersRow, error)
	LockUserAccount(ctx context.Context, arg LockUserAccountParams) error
	MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) error
	RemoveCollectionMember(ctx context.Context, arg RemoveCollectionMemberParams) error
	ResetFailedLoginAttempts(ctx context.Context, id pgtype.UUID) error
	RestoreDocument(ctx context.Context, id pgtype.UUID) error
	RevokeDocumentShare(ctx context.Context, arg RevokeDocumentShareParams) error
	SearchDocuments(ctx context.Context, arg SearchDocumentsParams) ([]SearchDocumentsRow, error)
	SearchDocumentsWithFilters(ctx context.Context, arg SearchDocumentsWithFiltersParams) ([]SearchDocumentsWithFiltersRow, error)
	SetDocumentCurrentVersion(ctx context.Context, arg SetDocumentCurrentVersionParams) error
	SetDocumentStatus(ctx context.Context, arg SetDocumentStatusParams) error
	ShareDocument(ctx context.Context, arg ShareDocumentParams) error
	SoftDeleteDocument(ctx context.Context, id pgtype.UUID) error
	UpdateCollection(ctx context.Context, arg UpdateCollectionParams) (Collection, error)
	UpdateDocumentCore(ctx context.Context, arg UpdateDocumentCoreParams) (Document, error)
	UpdateJobStatus(ctx context.Context, arg UpdateJobStatusParams) error
	UpdateUserLastLogin(ctx context.Context, id pgtype.UUID) error
	UpdateUserMFA(ctx context.Context, arg UpdateUserMFAParams) error
	UpsertOCRText(ctx context.Context, arg UpsertOCRTextParams) (OcrText, error)
	UpsertPreviewAsset(ctx context.Context, arg UpsertPreviewAssetParams) error
	UpsertQuota(ctx context.Context, arg UpsertQuotaParams) (Quota, error)
	UpsertRetentionPolicy(ctx context.Context, arg UpsertRetentionPolicyParams) (RetentionPolicy, error)
	UpsertSystemSetting(ctx context.Context, arg UpsertSystemSettingParams) (SystemSetting, error)
	UpsertTag(ctx context.Context, arg UpsertTagParams) (Tag, error)
}

var _ Querier = (*Queries)(nil)
