// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: search.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSavedSearch = `-- name: CreateSavedSearch :one
INSERT INTO saved_searches (
  org_id,
  user_id,
  name,
  query_text,
  filters_json
) VALUES ($1, $2, $3, $4, $5)
RETURNING id, org_id, user_id, name, query_text, filters_json, created_at, updated_at
`

type CreateSavedSearchParams struct {
	OrgID       pgtype.UUID `json:"org_id"`
	UserID      pgtype.UUID `json:"user_id"`
	Name        string      `json:"name"`
	QueryText   string      `json:"query_text"`
	FiltersJson []byte      `json:"filters_json"`
}

func (q *Queries) CreateSavedSearch(ctx context.Context, arg CreateSavedSearchParams) (SavedSearch, error) {
	row := q.db.QueryRow(ctx, createSavedSearch,
		arg.OrgID,
		arg.UserID,
		arg.Name,
		arg.QueryText,
		arg.FiltersJson,
	)
	var i SavedSearch
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UserID,
		&i.Name,
		&i.QueryText,
		&i.FiltersJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSavedSearch = `-- name: DeleteSavedSearch :exec
DELETE FROM saved_searches
WHERE id = $1
  AND user_id = $2
`

type DeleteSavedSearchParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteSavedSearch(ctx context.Context, arg DeleteSavedSearchParams) error {
	_, err := q.db.Exec(ctx, deleteSavedSearch, arg.ID, arg.UserID)
	return err
}

const listSavedSearches = `-- name: ListSavedSearches :many
SELECT id, org_id, user_id, name, query_text, filters_json, created_at, updated_at FROM saved_searches
WHERE user_id = $1
ORDER BY updated_at DESC
`

func (q *Queries) ListSavedSearches(ctx context.Context, userID pgtype.UUID) ([]SavedSearch, error) {
	rows, err := q.db.Query(ctx, listSavedSearches, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SavedSearch
	for rows.Next() {
		var i SavedSearch
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.UserID,
			&i.Name,
			&i.QueryText,
			&i.FiltersJson,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchDocuments = `-- name: SearchDocuments :many
SELECT DISTINCT
  d.id,
  d.title,
  d.original_filename,
  d.status,
  d.updated_at,
  COALESCE(ts_rank(d.search_vector, plainto_tsquery('simple', $5)), 0)
    + COALESCE(ts_rank(ot.search_vector, plainto_tsquery('simple', $5)), 0) AS rank,
  COALESCE(LEFT(ot.content, 200), '') AS snippet
FROM documents d
LEFT JOIN document_versions dv ON dv.id = d.current_version_id
LEFT JOIN ocr_text ot ON ot.document_version_id = dv.id
WHERE d.org_id = $1
  AND d.deleted_at IS NULL
  AND (
    $4::boolean
    OR d.owner_user_id = $2
    OR EXISTS (
      SELECT 1
      FROM collection_members cm
      WHERE cm.collection_id = d.collection_id
        AND cm.user_id = $2
    )
    OR EXISTS (
      SELECT 1
      FROM document_permissions dp
      WHERE dp.document_id = d.id
        AND dp.allow = true
        AND (
          (dp.subject_type = 'user' AND dp.subject_id = $2)
          OR (dp.subject_type = 'role' AND dp.subject_id = ANY($3::uuid[]))
        )
    )
  )
  AND (
    d.search_vector @@ plainto_tsquery('simple', $5)
    OR ot.search_vector @@ plainto_tsquery('simple', $5)
    OR EXISTS (
      SELECT 1
      FROM document_metadata dm
      WHERE dm.document_id = d.id
        AND coalesce(dm.value_text, '') ILIKE '%' || $5 || '%'
    )
  )
ORDER BY rank DESC, d.updated_at DESC
LIMIT $6 OFFSET $7
`

type SearchDocumentsParams struct {
	OrgID          pgtype.UUID   `json:"org_id"`
	OwnerUserID    pgtype.UUID   `json:"owner_user_id"`
	Column3        []pgtype.UUID `json:"column_3"`
	Column4        bool          `json:"column_4"`
	PlaintoTsquery string        `json:"plainto_tsquery"`
	Limit          int32         `json:"limit"`
	Offset         int32         `json:"offset"`
}

type SearchDocumentsRow struct {
	ID               pgtype.UUID        `json:"id"`
	Title            string             `json:"title"`
	OriginalFilename string             `json:"original_filename"`
	Status           string             `json:"status"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	Rank             int32              `json:"rank"`
	Snippet          interface{}        `json:"snippet"`
}

func (q *Queries) SearchDocuments(ctx context.Context, arg SearchDocumentsParams) ([]SearchDocumentsRow, error) {
	rows, err := q.db.Query(ctx, searchDocuments,
		arg.OrgID,
		arg.OwnerUserID,
		arg.Column3,
		arg.Column4,
		arg.PlaintoTsquery,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchDocumentsRow
	for rows.Next() {
		var i SearchDocumentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.OriginalFilename,
			&i.Status,
			&i.UpdatedAt,
			&i.Rank,
			&i.Snippet,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchDocumentsWithFilters = `-- name: SearchDocumentsWithFilters :many
SELECT DISTINCT
  d.id,
  d.title,
  d.original_filename,
  d.status,
  d.mime_type,
  d.updated_at,
  COALESCE(ts_rank(d.search_vector, plainto_tsquery('simple', $5)), 0)
    + COALESCE(ts_rank(ot.search_vector, plainto_tsquery('simple', $5)), 0) AS rank,
  COALESCE(LEFT(ot.content, 200), '') AS snippet
FROM documents d
LEFT JOIN document_versions dv ON dv.id = d.current_version_id
LEFT JOIN ocr_text ot ON ot.document_version_id = dv.id
WHERE d.org_id = $1
  AND d.deleted_at IS NULL
  AND (
    $4::boolean
    OR d.owner_user_id = $2
    OR EXISTS (
      SELECT 1 FROM collection_members cm
      WHERE cm.collection_id = d.collection_id AND cm.user_id = $2
    )
    OR EXISTS (
      SELECT 1 FROM document_permissions dp
      WHERE dp.document_id = d.id AND dp.allow = true
        AND ((dp.subject_type = 'user' AND dp.subject_id = $2) OR (dp.subject_type = 'role' AND dp.subject_id = ANY($3::uuid[])))
    )
  )
  AND (
    $5::text = ''
    OR d.search_vector @@ plainto_tsquery('simple', $5)
    OR ot.search_vector @@ plainto_tsquery('simple', $5)
  )
  AND ($8::text = '' OR d.status = $8)
  AND ($9::text = '' OR d.mime_type = $9)
  AND ($10::timestamptz IS NULL OR d.updated_at >= $10)
  AND ($11::timestamptz IS NULL OR d.updated_at <= $11)
ORDER BY rank DESC, d.updated_at DESC
LIMIT $6 OFFSET $7
`

type SearchDocumentsWithFiltersParams struct {
	OrgID          pgtype.UUID        `json:"org_id"`
	OwnerUserID    pgtype.UUID        `json:"owner_user_id"`
	Column3        []pgtype.UUID      `json:"column_3"`
	Column4        bool               `json:"column_4"`
	PlaintoTsquery string             `json:"plainto_tsquery"`
	Limit          int32              `json:"limit"`
	Offset         int32              `json:"offset"`
	Column8        string             `json:"column_8"`
	Column9        string             `json:"column_9"`
	Column10       pgtype.Timestamptz `json:"column_10"`
	Column11       pgtype.Timestamptz `json:"column_11"`
}

type SearchDocumentsWithFiltersRow struct {
	ID               pgtype.UUID        `json:"id"`
	Title            string             `json:"title"`
	OriginalFilename string             `json:"original_filename"`
	Status           string             `json:"status"`
	MimeType         string             `json:"mime_type"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	Rank             int32              `json:"rank"`
	Snippet          interface{}        `json:"snippet"`
}

func (q *Queries) SearchDocumentsWithFilters(ctx context.Context, arg SearchDocumentsWithFiltersParams) ([]SearchDocumentsWithFiltersRow, error) {
	rows, err := q.db.Query(ctx, searchDocumentsWithFilters,
		arg.OrgID,
		arg.OwnerUserID,
		arg.Column3,
		arg.Column4,
		arg.PlaintoTsquery,
		arg.Limit,
		arg.Offset,
		arg.Column8,
		arg.Column9,
		arg.Column10,
		arg.Column11,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchDocumentsWithFiltersRow
	for rows.Next() {
		var i SearchDocumentsWithFiltersRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.OriginalFilename,
			&i.Status,
			&i.MimeType,
			&i.UpdatedAt,
			&i.Rank,
			&i.Snippet,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
