// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: teams.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addRolePermission = `-- name: AddRolePermission :exec
INSERT INTO role_permissions (role_id, permission_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddRolePermissionParams struct {
	RoleID       pgtype.UUID `json:"role_id"`
	PermissionID pgtype.UUID `json:"permission_id"`
}

func (q *Queries) AddRolePermission(ctx context.Context, arg AddRolePermissionParams) error {
	_, err := q.db.Exec(ctx, addRolePermission, arg.RoleID, arg.PermissionID)
	return err
}

const claimTeamInvite = `-- name: ClaimTeamInvite :one
UPDATE team_invites
SET use_count = use_count + 1
WHERE code = $1
  AND (max_uses = 0 OR use_count < max_uses)
  AND expires_at > now()
RETURNING id, org_id, code, created_by, expires_at, max_uses, use_count, created_at
`

func (q *Queries) ClaimTeamInvite(ctx context.Context, code string) (TeamInvite, error) {
	row := q.db.QueryRow(ctx, claimTeamInvite, code)
	var i TeamInvite
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Code,
		&i.CreatedBy,
		&i.ExpiresAt,
		&i.MaxUses,
		&i.UseCount,
		&i.CreatedAt,
	)
	return i, err
}

const clearOrgUsers = `-- name: ClearOrgUsers :exec
UPDATE users
SET org_id = NULL, updated_at = now()
WHERE org_id = $1
`

func (q *Queries) ClearOrgUsers(ctx context.Context, orgID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearOrgUsers, orgID)
	return err
}

const createDefaultQuota = `-- name: CreateDefaultQuota :one
INSERT INTO quotas (org_id, target_type, max_storage_bytes, max_document_count)
VALUES ($1, 'org', 10737418240, 50000)
RETURNING id, org_id, target_type, target_id, max_storage_bytes, max_document_count, created_at, updated_at
`

func (q *Queries) CreateDefaultQuota(ctx context.Context, orgID pgtype.UUID) (Quota, error) {
	row := q.db.QueryRow(ctx, createDefaultQuota, orgID)
	var i Quota
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.TargetType,
		&i.TargetID,
		&i.MaxStorageBytes,
		&i.MaxDocumentCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createGoogleUser = `-- name: CreateGoogleUser :one
INSERT INTO users (email, full_name, google_id, avatar_url, password_hash, status)
VALUES ($1, $2, $3, $4, '', 'active')
RETURNING id, org_id, email, full_name, password_hash, mfa_enabled, mfa_secret_encrypted, status, created_at, updated_at, last_login_at, failed_login_attempts, locked_until, google_id, avatar_url
`

type CreateGoogleUserParams struct {
	Email     string      `json:"email"`
	FullName  string      `json:"full_name"`
	GoogleID  pgtype.Text `json:"google_id"`
	AvatarUrl string      `json:"avatar_url"`
}

func (q *Queries) CreateGoogleUser(ctx context.Context, arg CreateGoogleUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createGoogleUser,
		arg.Email,
		arg.FullName,
		arg.GoogleID,
		arg.AvatarUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Email,
		&i.FullName,
		&i.PasswordHash,
		&i.MfaEnabled,
		&i.MfaSecretEncrypted,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.GoogleID,
		&i.AvatarUrl,
	)
	return i, err
}

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO organizations (name, slug)
VALUES ($1, $2)
RETURNING id, name, slug, created_at
`

type CreateOrganizationParams struct {
	Name string `json:"name"`
	Slug string `json:"slug"`
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, createOrganization, arg.Name, arg.Slug)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
	)
	return i, err
}

const createRole = `-- name: CreateRole :one
INSERT INTO roles (org_id, key, name, description)
VALUES ($1, $2, $3, $4)
RETURNING id, org_id, key, name, description, created_at
`

type CreateRoleParams struct {
	OrgID       pgtype.UUID `json:"org_id"`
	Key         string      `json:"key"`
	Name        string      `json:"name"`
	Description string      `json:"description"`
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, createRole,
		arg.OrgID,
		arg.Key,
		arg.Name,
		arg.Description,
	)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const createTeamInvite = `-- name: CreateTeamInvite :one
INSERT INTO team_invites (org_id, code, created_by, expires_at, max_uses)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, org_id, code, created_by, expires_at, max_uses, use_count, created_at
`

type CreateTeamInviteParams struct {
	OrgID     pgtype.UUID        `json:"org_id"`
	Code      string             `json:"code"`
	CreatedBy pgtype.UUID        `json:"created_by"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	MaxUses   int32              `json:"max_uses"`
}

func (q *Queries) CreateTeamInvite(ctx context.Context, arg CreateTeamInviteParams) (TeamInvite, error) {
	row := q.db.QueryRow(ctx, createTeamInvite,
		arg.OrgID,
		arg.Code,
		arg.CreatedBy,
		arg.ExpiresAt,
		arg.MaxUses,
	)
	var i TeamInvite
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Code,
		&i.CreatedBy,
		&i.ExpiresAt,
		&i.MaxUses,
		&i.UseCount,
		&i.CreatedAt,
	)
	return i, err
}

const deleteInvitesByOrg = `-- name: DeleteInvitesByOrg :exec
DELETE FROM team_invites WHERE org_id = $1
`

func (q *Queries) DeleteInvitesByOrg(ctx context.Context, orgID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteInvitesByOrg, orgID)
	return err
}

const deleteOrganization = `-- name: DeleteOrganization :exec
DELETE FROM organizations WHERE id = $1
`

func (q *Queries) DeleteOrganization(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteOrganization, id)
	return err
}

const deleteQuotasByOrg = `-- name: DeleteQuotasByOrg :exec
DELETE FROM quotas WHERE org_id = $1
`

func (q *Queries) DeleteQuotasByOrg(ctx context.Context, orgID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteQuotasByOrg, orgID)
	return err
}

const deleteRolesByOrg = `-- name: DeleteRolesByOrg :exec
DELETE FROM roles WHERE org_id = $1
`

func (q *Queries) DeleteRolesByOrg(ctx context.Context, orgID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteRolesByOrg, orgID)
	return err
}

const ensureGlobalPermissions = `-- name: EnsureGlobalPermissions :exec
INSERT INTO permissions (id, key, description)
VALUES
  ('20000000-0000-0000-0000-000000000001', 'documents.read', 'Read documents'),
  ('20000000-0000-0000-0000-000000000002', 'documents.write', 'Create and update documents'),
  ('20000000-0000-0000-0000-000000000003', 'documents.admin', 'Archive and restore documents'),
  ('20000000-0000-0000-0000-000000000004', 'audit.read', 'Read audit logs'),
  ('20000000-0000-0000-0000-000000000005', 'admin.manage', 'Manage users and settings')
ON CONFLICT (id) DO NOTHING
`

func (q *Queries) EnsureGlobalPermissions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, ensureGlobalPermissions)
	return err
}

const getOrganizationByID = `-- name: GetOrganizationByID :one
SELECT id, name, slug, created_at FROM organizations
WHERE id = $1
`

func (q *Queries) GetOrganizationByID(ctx context.Context, id pgtype.UUID) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationByID, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
	)
	return i, err
}

const getPermissionByKey = `-- name: GetPermissionByKey :one
SELECT id, key, description FROM permissions
WHERE key = $1
`

func (q *Queries) GetPermissionByKey(ctx context.Context, key string) (Permission, error) {
	row := q.db.QueryRow(ctx, getPermissionByKey, key)
	var i Permission
	err := row.Scan(&i.ID, &i.Key, &i.Description)
	return i, err
}

const getRoleByOrgAndKey = `-- name: GetRoleByOrgAndKey :one
SELECT id, org_id, key, name, description, created_at FROM roles
WHERE org_id = $1 AND key = $2
`

type GetRoleByOrgAndKeyParams struct {
	OrgID pgtype.UUID `json:"org_id"`
	Key   string      `json:"key"`
}

func (q *Queries) GetRoleByOrgAndKey(ctx context.Context, arg GetRoleByOrgAndKeyParams) (Role, error) {
	row := q.db.QueryRow(ctx, getRoleByOrgAndKey, arg.OrgID, arg.Key)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getTeamInviteByCode = `-- name: GetTeamInviteByCode :one
SELECT id, org_id, code, created_by, expires_at, max_uses, use_count, created_at FROM team_invites
WHERE code = $1
`

func (q *Queries) GetTeamInviteByCode(ctx context.Context, code string) (TeamInvite, error) {
	row := q.db.QueryRow(ctx, getTeamInviteByCode, code)
	var i TeamInvite
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Code,
		&i.CreatedBy,
		&i.ExpiresAt,
		&i.MaxUses,
		&i.UseCount,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByGoogleID = `-- name: GetUserByGoogleID :one
SELECT id, org_id, email, full_name, password_hash, mfa_enabled, mfa_secret_encrypted, status, created_at, updated_at, last_login_at, failed_login_attempts, locked_until, google_id, avatar_url FROM users
WHERE google_id = $1
`

func (q *Queries) GetUserByGoogleID(ctx context.Context, googleID pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByGoogleID, googleID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Email,
		&i.FullName,
		&i.PasswordHash,
		&i.MfaEnabled,
		&i.MfaSecretEncrypted,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.GoogleID,
		&i.AvatarUrl,
	)
	return i, err
}

const listAllPermissions = `-- name: ListAllPermissions :many
SELECT id, key, description FROM permissions
ORDER BY key
`

func (q *Queries) ListAllPermissions(ctx context.Context) ([]Permission, error) {
	rows, err := q.db.Query(ctx, listAllPermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Permission
	for rows.Next() {
		var i Permission
		if err := rows.Scan(&i.ID, &i.Key, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamMembers = `-- name: ListTeamMembers :many
SELECT
  u.id,
  u.email,
  u.full_name,
  u.avatar_url,
  u.status,
  u.created_at,
  COALESCE(array_remove(array_agg(r.key), NULL), ARRAY[]::text[])::text[] AS role_keys
FROM users u
LEFT JOIN user_roles ur ON ur.user_id = u.id
LEFT JOIN roles r ON r.id = ur.role_id
WHERE u.org_id = $1
GROUP BY u.id
ORDER BY u.created_at
`

type ListTeamMembersRow struct {
	ID        pgtype.UUID        `json:"id"`
	Email     string             `json:"email"`
	FullName  string             `json:"full_name"`
	AvatarUrl string             `json:"avatar_url"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	RoleKeys  []string           `json:"role_keys"`
}

func (q *Queries) ListTeamMembers(ctx context.Context, orgID pgtype.UUID) ([]ListTeamMembersRow, error) {
	rows, err := q.db.Query(ctx, listTeamMembers, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTeamMembersRow
	for rows.Next() {
		var i ListTeamMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.FullName,
			&i.AvatarUrl,
			&i.Status,
			&i.CreatedAt,
			&i.RoleKeys,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTeamMember = `-- name: RemoveTeamMember :exec
UPDATE users
SET org_id = NULL, updated_at = now()
WHERE id = $1 AND org_id = $2
`

type RemoveTeamMemberParams struct {
	ID    pgtype.UUID `json:"id"`
	OrgID pgtype.UUID `json:"org_id"`
}

func (q *Queries) RemoveTeamMember(ctx context.Context, arg RemoveTeamMemberParams) error {
	_, err := q.db.Exec(ctx, removeTeamMember, arg.ID, arg.OrgID)
	return err
}

const setUserOrg = `-- name: SetUserOrg :exec
UPDATE users
SET org_id = $2, updated_at = now()
WHERE id = $1
`

type SetUserOrgParams struct {
	ID    pgtype.UUID `json:"id"`
	OrgID pgtype.UUID `json:"org_id"`
}

func (q *Queries) SetUserOrg(ctx context.Context, arg SetUserOrgParams) error {
	_, err := q.db.Exec(ctx, setUserOrg, arg.ID, arg.OrgID)
	return err
}

const updateMemberRole = `-- name: UpdateMemberRole :exec
UPDATE user_roles
SET role_id = $2
WHERE user_id = $1
`

type UpdateMemberRoleParams struct {
	UserID pgtype.UUID `json:"user_id"`
	RoleID pgtype.UUID `json:"role_id"`
}

func (q *Queries) UpdateMemberRole(ctx context.Context, arg UpdateMemberRoleParams) error {
	_, err := q.db.Exec(ctx, updateMemberRole, arg.UserID, arg.RoleID)
	return err
}

const updateOrganization = `-- name: UpdateOrganization :one
UPDATE organizations
SET name = $2, slug = $3
WHERE id = $1
RETURNING id, name, slug, created_at
`

type UpdateOrganizationParams struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
	Slug string      `json:"slug"`
}

func (q *Queries) UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, updateOrganization, arg.ID, arg.Name, arg.Slug)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
	)
	return i, err
}
