// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addUserRole = `-- name: AddUserRole :exec
INSERT INTO user_roles (user_id, role_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddUserRoleParams struct {
	UserID pgtype.UUID `json:"user_id"`
	RoleID pgtype.UUID `json:"role_id"`
}

func (q *Queries) AddUserRole(ctx context.Context, arg AddUserRoleParams) error {
	_, err := q.db.Exec(ctx, addUserRole, arg.UserID, arg.RoleID)
	return err
}

const deleteUserRolesByUserID = `-- name: DeleteUserRolesByUserID :exec
DELETE FROM user_roles
WHERE user_id = $1
`

func (q *Queries) DeleteUserRolesByUserID(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserRolesByUserID, userID)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, org_id, email, full_name, password_hash, mfa_enabled, mfa_secret_encrypted, status, created_at, updated_at, last_login_at, failed_login_attempts, locked_until FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Email,
		&i.FullName,
		&i.PasswordHash,
		&i.MfaEnabled,
		&i.MfaSecretEncrypted,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, org_id, email, full_name, password_hash, mfa_enabled, mfa_secret_encrypted, status, created_at, updated_at, last_login_at, failed_login_attempts, locked_until FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Email,
		&i.FullName,
		&i.PasswordHash,
		&i.MfaEnabled,
		&i.MfaSecretEncrypted,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
	)
	return i, err
}

const incrementFailedLoginAttempts = `-- name: IncrementFailedLoginAttempts :exec
UPDATE users
SET failed_login_attempts = COALESCE(failed_login_attempts, 0) + 1,
    updated_at = now()
WHERE id = $1
`

func (q *Queries) IncrementFailedLoginAttempts(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, incrementFailedLoginAttempts, id)
	return err
}

const listPermissionsByRoleIDs = `-- name: ListPermissionsByRoleIDs :many
SELECT DISTINCT p.id, p.key, p.description
FROM permissions p
JOIN role_permissions rp ON rp.permission_id = p.id
WHERE rp.role_id = ANY($1::uuid[])
ORDER BY p.key
`

func (q *Queries) ListPermissionsByRoleIDs(ctx context.Context, dollar_1 []pgtype.UUID) ([]Permission, error) {
	rows, err := q.db.Query(ctx, listPermissionsByRoleIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Permission
	for rows.Next() {
		var i Permission
		if err := rows.Scan(&i.ID, &i.Key, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoles = `-- name: ListRoles :many
SELECT id, org_id, key, name, description, created_at FROM roles
WHERE org_id = $1
ORDER BY name
`

func (q *Queries) ListRoles(ctx context.Context, orgID pgtype.UUID) ([]Role, error) {
	rows, err := q.db.Query(ctx, listRoles, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Key,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserRoles = `-- name: ListUserRoles :many
SELECT r.id, r.org_id, r.key, r.name, r.description, r.created_at
FROM roles r
JOIN user_roles ur ON ur.role_id = r.id
WHERE ur.user_id = $1
ORDER BY r.name
`

func (q *Queries) ListUserRoles(ctx context.Context, userID pgtype.UUID) ([]Role, error) {
	rows, err := q.db.Query(ctx, listUserRoles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Key,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT
  u.id,
  u.org_id,
  u.email,
  u.full_name,
  u.mfa_enabled,
  u.status,
  u.created_at,
  u.updated_at,
  u.last_login_at,
  COALESCE(array_remove(array_agg(r.name), NULL), ARRAY[]::text[])::text[] AS role_names
FROM users u
LEFT JOIN user_roles ur ON ur.user_id = u.id
LEFT JOIN roles r ON r.id = ur.role_id
WHERE u.org_id = $1
GROUP BY u.id
ORDER BY u.created_at DESC
`

type ListUsersRow struct {
	ID          pgtype.UUID        `json:"id"`
	OrgID       pgtype.UUID        `json:"org_id"`
	Email       string             `json:"email"`
	FullName    string             `json:"full_name"`
	MfaEnabled  bool               `json:"mfa_enabled"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	LastLoginAt pgtype.Timestamptz `json:"last_login_at"`
	RoleNames   []string           `json:"role_names"`
}

func (q *Queries) ListUsers(ctx context.Context, orgID pgtype.UUID) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Email,
			&i.FullName,
			&i.MfaEnabled,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastLoginAt,
			&i.RoleNames,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockUserAccount = `-- name: LockUserAccount :exec
UPDATE users
SET locked_until = $2,
    updated_at = now()
WHERE id = $1
`

type LockUserAccountParams struct {
	ID          pgtype.UUID        `json:"id"`
	LockedUntil pgtype.Timestamptz `json:"locked_until"`
}

func (q *Queries) LockUserAccount(ctx context.Context, arg LockUserAccountParams) error {
	_, err := q.db.Exec(ctx, lockUserAccount, arg.ID, arg.LockedUntil)
	return err
}

const resetFailedLoginAttempts = `-- name: ResetFailedLoginAttempts :exec
UPDATE users
SET failed_login_attempts = 0,
    locked_until = NULL,
    updated_at = now()
WHERE id = $1
`

func (q *Queries) ResetFailedLoginAttempts(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, resetFailedLoginAttempts, id)
	return err
}

const updateUserLastLogin = `-- name: UpdateUserLastLogin :exec
UPDATE users
SET last_login_at = now(), updated_at = now()
WHERE id = $1
`

func (q *Queries) UpdateUserLastLogin(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateUserLastLogin, id)
	return err
}

const updateUserMFA = `-- name: UpdateUserMFA :exec
UPDATE users
SET mfa_enabled = $2,
    mfa_secret_encrypted = $3,
    updated_at = now()
WHERE id = $1
`

type UpdateUserMFAParams struct {
	ID                 pgtype.UUID `json:"id"`
	MfaEnabled         bool        `json:"mfa_enabled"`
	MfaSecretEncrypted []byte      `json:"mfa_secret_encrypted"`
}

func (q *Queries) UpdateUserMFA(ctx context.Context, arg UpdateUserMFAParams) error {
	_, err := q.db.Exec(ctx, updateUserMFA, arg.ID, arg.MfaEnabled, arg.MfaSecretEncrypted)
	return err
}
